spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes[0]:
        id: book-service
        uri: lb://book-service
        predicates: Path=/api/book/**

      routes[1]:
        id: inventory-service
        uri: lb://inventory-service
        predicates: Path=/api/inventory/**

      routes[2]:
        id: loan-service
        uri: lb://loan-service
        predicates: Path=/api/loan/**

      routes[3]:
        id: discovery-server
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/

      routes[4]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm


eureka:
  client:
    service-url:
        defaultZone: http://eureka:password@localhost:8761/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info



management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: prometheus
