spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/food-service
    application:
        name: book-service

eureka:
    client:
        service-url:
            defaultZone: http://eureka:password@localhost:8761/eureka/
server:
    port: 8282

management:
    tracing:
        sampling:
            probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
    endpoints:
      web:
        exposure:
            include: prometheus