spring:
  cassandra:
    keyspace-name: loan
    schema-action: create_if_not_exists
    port: 9042
    username: cassandra
    password: cassandra
    contact-points: localhost
    local-datacenter: datacenter1
  application:
    name: loan-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:org.ratnesh.loanservice.event.LoanNotification



management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/